# Generated by Django 5.0.9 on 2024-10-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='reception_times',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=20)),
                ('app_url', models.URLField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='management.staff')),
            ],
        ),
    ]
