# Generated by Django 5.0.9 on 2024-10-13 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyCategory',
            fields=[
                ('subcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='labeler.subcategory')),
                ('sub_category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='labeler.subcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('labeler.subcategory',),
        ),
        migrations.CreateModel(
            name='AgencyCategoryThrouh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_category_name', models.CharField(max_length=300)),
                ('agency_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.agencycategory')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.staff')),
            ],
        ),
        migrations.AddField(
            model_name='agencycategory',
            name='staffs',
            field=models.ManyToManyField(blank=True, related_name='agency_categories', through='management.AgencyCategoryThrouh', to='management.staff'),
        ),
    ]
