# Generated by Django 5.0.9 on 2024-10-15 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='sub_menu_category',
        ),
    ]
