# Generated by Django 5.0.9 on 2024-10-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_new_age_limit_new_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='NewCategory',
        ),
    ]
