# Generated by Django 5.0.9 on 2024-10-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_new_sub_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcategory',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
