# Generated by Django 5.0.9 on 2024-10-12 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0002_subcategory_parent_category'),
        ('news', '0003_rename_category_newcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='sub_menu_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labeler.subcategory'),
        ),
    ]
