# Generated by Django 5.0.9 on 2024-10-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcategory',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
