# Generated by Django 5.0.9 on 2024-10-20 05:17

import django.db.models.deletion
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newcategory_name_alter_newcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=news.models.new_image_path)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.new')),
            ],
        ),
    ]
