# Generated by Django 5.0.9 on 2024-10-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcategory',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
