# Generated by Django 5.0.9 on 2024-10-12 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='labeler.rootcategory'),
        ),
    ]
