# Generated by Django 5.0.9 on 2024-10-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('labeler', '0001_initial'),
        ('news', '0001_initial'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsThroughTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsThroughTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.new')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, through='labeler.DocumentsThroughTable', to='documents.document')),
                ('news', models.ManyToManyField(blank=True, through='labeler.NewsThroughTable', to='news.new')),
                ('sub_category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='labeler.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='newsthroughtable',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeler.page'),
        ),
        migrations.AddField(
            model_name='documentsthroughtable',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeler.page'),
        ),
        migrations.CreateModel(
            name='PollsThroughTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeler.page')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='polls',
            field=models.ManyToManyField(blank=True, through='labeler.PollsThroughTable', to='polls.poll'),
        ),
        migrations.CreateModel(
            name='StaffsThroughTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('staff_category', models.CharField(blank=True, max_length=300, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeler.page')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='staffs',
            field=models.ManyToManyField(blank=True, through='labeler.StaffsThroughTable', to='management.staff'),
        ),
    ]
