# Generated by Django 5.0.9 on 2024-10-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0002_documentsthroughtable_newsthroughtable_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
