# Generated by Django 5.0.9 on 2024-10-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0002_subcategory_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
