# Generated by Django 5.0.9 on 2024-10-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0003_page_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
