# Generated by Django 5.0.9 on 2024-10-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0004_page_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcategory',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
