# Generated by Django 5.0.9 on 2024-10-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0005_rootcategory_slug_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
