# Generated by Django 5.0.9 on 2024-10-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_simpledocument'),
        ('labeler', '0008_customtable_page_tables_customtablefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='simple_documents',
            field=models.ManyToManyField(blank=True, to='documents.simpledocument'),
        ),
    ]
