# Generated by Django 5.0.9 on 2024-10-28 03:25

import django.db.models.deletion
import labeler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0009_page_simple_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=labeler.models.page_image_path)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeler.page')),
            ],
        ),
    ]
