# Generated by Django 5.0.9 on 2024-10-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0010_pageimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsthroughtable',
            options={'verbose_name': 'Page Document', 'verbose_name_plural': 'Page Documents'},
        ),
        migrations.AlterModelOptions(
            name='newsthroughtable',
            options={'verbose_name': 'Page New', 'verbose_name_plural': 'Page News'},
        ),
        migrations.AlterModelOptions(
            name='pollsthroughtable',
            options={'verbose_name': 'Page Poll', 'verbose_name_plural': 'Page Polls'},
        ),
        migrations.AlterModelOptions(
            name='staffsthroughtable',
            options={'verbose_name': 'Page Staff', 'verbose_name_plural': 'Page Staffs'},
        ),
    ]
