# Generated by Django 5.0.9 on 2024-10-30 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0011_alter_documentsthroughtable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTableFieldHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='customtablefield',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='labeler.customtablefieldhead'),
        ),
    ]
