# Generated by Django 5.0.9 on 2024-11-01 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_commonquestion'),
        ('labeler', '0012_customtablefieldhead_customtablefield_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonQuestionThroughTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeler.page')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeals.commonquestion')),
            ],
            options={
                'verbose_name': 'Page Common Question',
                'verbose_name_plural': 'Page Common Questions',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='common_questions',
            field=models.ManyToManyField(blank=True, through='labeler.CommonQuestionThroughTable', to='appeals.commonquestion'),
        ),
    ]
