# Generated by Django 5.0.9 on 2024-10-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='DocumentCategory',
        ),
    ]
