# Generated by Django 5.0.9 on 2024-10-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_issued_date_alter_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
