# Generated by Django 5.0.9 on 2024-10-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
