# Generated by Django 5.0.9 on 2024-10-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_simpledocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='simpledocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
