# Generated by Django 5.0.9 on 2024-10-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
