# Generated by Django 5.0.9 on 2024-10-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('work_address', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('JR', 'Jarayonda'), ('HQ', 'Ijobiy hal qilingan\t'), ('MB', "Huquqiy ma'lumot berilgan"), ('TB', 'Tushuntirish berilgan'), ('RE', 'Rad etilgan'), ('BH', "Boshqa holatlar bo'yicha")], default='JR', max_length=2)),
            ],
        ),
    ]
