# Generated by Django 5.0.9 on 2024-11-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_appeal_created_appeal_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
