# Generated by Django 5.0.9 on 2024-11-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_commonquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealStatisticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
